### ISSUE TITLE
I know it says only Windows 7, but doesn't work with Windows 10

### ISSUE THREAD

**Issue by jonathancolledge** [pacsdisplay/pacsdisplay#1]
This works really well with Windows 7, but LumResponse and i1meter don't work with Windows 10. I tried repackaging into a new Starpack and it still doesn't like the i1Display Pro (which works fine on Windows 7). Spotread also works fine on Windows 10. Compatibility mode doesn't work.

This is what i1meter says:

can't read "expect_out(buffer)": no such variable
can't read "expect_out(buffer)": no such variable
    while executing
"puts $expect_out(buffer)"
    (procedure "iOneInit" line 52)
    invoked from within
"iOneInit BIN-LR $mode"
    (procedure "startMeter" line 17)
    invoked from within
"startMeter BIN-LR $ioneLmode"
    invoked from within
".cmdbar.start invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 24)
    invoked from within
"tk::ButtonUp .cmdbar.start"
    (command bound to event)

**Comment by nickbevins** [comment]
Hi Jonathon,

Yes, we are aware it doesn't work with Windows 10. We suspect that it's related to the expect procedure. Mike and I have discussed the possibility of re-working the code to eliminate the need for expect, but it is not a small undertaking. If you think you'd be interested in contributing to the code, please let us know.

**Comment by jonathancolledge** [comment]
Thanks, contributing is out of my league I'm afraid! I'm trying to find a legal copy of Windows 7 (tricky nowdays) so hopeful that'll do.

Jonathan

-----Original Message-----

**Comment by nlellis8** [comment]
I am not a programmer but I would be possibly interested in financial contribution to help with a windows 10 version that will work with the X-Rite eye-one pro (ES-1000).  I work with dental clients and would like to be able to calibrate their monitors for better detection of carries and other dental related issues when viewing images from digital sensors and digital panoramic devices.  Currently the dental industry does not seem to put a lot of importance in the calibration of the actual display. Most dealers will calibrate the digital device and then make visual adjustments that make the dentist happy.  They are totally missing out on the possibility of displaying images that have superior grey levels and ability to easily diagnose problems and be able to find problems they may never see on an uncalibrated display.  Most of my clients are using windows 7 but are gradually moving to windows 10.

**Comment by nlellis8** [comment]
Also, I would be interested in financing a possible dental only version that can be easily installed and based on picking one spectrophotometer like even a Spyder 5 Pro or Color-monkey.  Essentially, apart from my own interest in getting the program to work in windows 10 with my eye-one pro, I would like to know if there is anyone that can work with the open source software and develop a dental specific package based on one device and possible a choice of 6-12 monitor models so I can implement a calibration program and possibly a monitoring service specific to dental industry.  Also I have no idea if I am totally out of like in what I am asking and if this is allowed to be discussed in this forum.  Newbee I am :)  Neil Ellis - nlellis8@hotmail.com

**Comment by nickbevins** [comment]
Hi Neil - Thanks for the comments. I know we need to move the platform to be compatible with W10, but just haven't had a chance to do it. As I mentioned in a previous post, it's not a small undertaking. 

Regarding the "dental-only" version, I think you should be able to accomplish what you'd like with the program now, except we don't necessarily support all of the devices you've discussed. If you have a standard set of displays that you find in the field, setting up generic versions in the LUT library should allow you to automatically load a calibrated LUT even to a display that hasn't been individually characterized.

**Comment by nickbevins** [comment]
The Windows 10 issue should be solved - I think. Please download the latest version and try again.
