### ISSUE TITLE
Calibrite ColorChecker Display Plus VS X-rite i1 Display Pro

### ISSUE THREAD

**Issue by Jakopce** [pacsdisplay/pacsdisplay#10]
Hello, 
I have quick ask, 
I wanna buy a colorometer, and now in my country its pretty hard to get old X-Rite i1, and i think about buy Calibrite Display Plus, its easy to get and support OLED (this will be fine to calibrate TV etc). 
And Calibrite is compatible with pacs display? 

Greets
Jackob.

**Comment by nickbevins** [comment]
Greetings Jackob - 

Yes, the i1DisplayPro now seems to be made by Calibrite. I don't own any of these photometers, so I cannot say for certain they will work. However, the same device is sold under many names (NEC Spectrasensor Pro https://www.bhphotovideo.com/c/product/827959-REG/NEC_MDSVSENSOR3_SpectraSensor_Pro_Color_Calibration.html, for example). These devices also work with pacsDisplay, so I would guess that the new device will also work. I can try to get my hands on one, but you should be ok to use it.

Please reply if you are unsuccessful and I can be sure to work on making sure the new device is compatible. 

Thanks,
Nick

**Comment by nickbevins** [comment]
Hi Jackob - 

Did you ever buy a photometer? I'm curious if the Calibrite sensor worked with pacsDisplay. 

Best,
Nick

**Comment by Jakopce** [comment]
> Hi Jackob -
> 
> Did you ever buy a photometer? I'm curious if the Calibrite sensor worked with pacsDisplay.
> 
> Best, Nick

Im sorry, i forget about this post.  
Works fine, program see this as "i1Display Pro Photometer", but show real values (i duble check in displaycal and hcfr).
