### ISSUE TITLE
lumResponse Hangs on Gray Level 207

### ISSUE THREAD

**Issue by coppclark** [pacsdisplay/pacsdisplay#2]
Hey Nick

I am pumped about Win10 version, but I am having an issue. LumResponse churns away on the measurements, but then hangs on gray level 207. Hangs every time at the same stage and on both monitors on this system.

Any suggestions on what I can try? I do not see any log file or error message.

Happy to debug myself (but do not have code).

Thanks
John Clark

**Comment by nickbevins** [comment]
Hi John

Can you provide any more details on what mode you're using in lumresponse? Have you seen the same error on other machines?

The exe files are starpacks, so you can use sdx.kit to unwrap them for the source code if you want to dig in. If not, just let me know what mode and I can poke around to see what I find.

Thanks
Nick

**Comment by coppclark** [comment]
Nick

Thanks for the quick response.

I am trying to use LumResponse with Mode 1786 to calibrate system with a Dell U3011 and Dell 2007 with a i1Display Pro

Everything hangs on Gray Level 207, Sub 4 (step 1456). The program does not crash, just waits forever. I can click Stop and it warns me that measurement is not completed.

I have not had time to play with debug but I would like to. I have little experience with TCL, but I will look at that as an opportunity for learning!

Thanks

John

________________________________

**Comment by nickbevins** [comment]
Coincidentally, I just had one other person contact me saying they had a similar issue. I’ll try to recreate on Monday when I get into the office. I’m hoping to push out an update w a fix by the end of next week.

Best

Nick

________________________________

**Comment by coppclark** [comment]
Just a follow up to let you know what success (and failure) I have had with hacking around a bit.

I was noticing that in proc IL_auto, that after the call to iOneCall, there is:

if {$error != 0 || $record == 0} break

That line would result in a silent failure if either error conditions were met. That seems to be a likely cause for the behaviour I am seeing.

So…I added a simple output message for this condition to see what the return error was. Unfortunately (or fortunately), when I ran this through tclkitsh then lumResponse ran without a hitch. That allowed me to complete calibration, but just not as pretty.

So there may be something with iOneCall that does not like being starpack wrapped? Pretty strange…

John

**Comment by nickbevins** [comment]
Hi John -

Where did you get the tclkitsh file? Was it the one that was wrapped with
the application? or did you find another online?

-Nick

**Comment by nickbevins** [comment]
Version 5D uses an updated tclkit as part of the starpack (64-bit). This appears to have resolved the hang up near gray level 207. The issue was not repeatable to the same gray level every time, suggesting a possible issue with the interpreter. Please try the newest version and confirm.

**Comment by coppclark** [comment]
Thanks

The tclkit is resolved, but I did I was really think I did right!

**Comment by nickbevins** [comment]
Thanks for your assistance in troubleshooting and correcting.
