### ISSUE TITLE
No DICOM curve plot

### ISSUE THREAD

**Issue by jonathancolledge** [pacsdisplay/pacsdisplay#4]
Suddenly I can't get the results plots from lumresponse 
![uLR-Plot-dL_L](https://user-images.githubusercontent.com/4342400/91334577-18df0a80-e7c7-11ea-8bf1-18b555901a67.png)

Can you help please? It used to work for me and now it doesn't no matter which computer or what version of PACSDisplay

**Comment by jonathancolledge** [comment]
These are the data (sorry I can't attach txt files so I'm just pasting:

**Comment by jonathancolledge** [comment]
#  lumResponse vers. 2.2 - 08/26/2020 08:25:30
#  Display ID: MDCC-6230
#  iLdelay=0  avgN=1  ILlimit_plus=0.20 ILlimit_minus=-0.05  Meter=i1DisplayPro LUTmode=256
#  0.569365  #000000
#  0.569179  #000000
#  0.569615  #000000
   1     0.5694650  #000000    1 1  0.0000   0.1815060   0.4137270
   2     0.6190240  #010101    2 1  0.0834   0.1823800   0.4175820
   3     0.6648200  #020202    3 1  0.0713   0.1830940   0.4206380
   4     0.7213560  #030303    4 1  0.0816   0.1837110   0.4243180
   5     0.7736570  #040404    5 1  0.0700   0.1835930   0.4270690
   6     0.8377200  #050505    6 1  0.0795   0.1844630   0.4300190
   7     0.8942260  #060606    7 1  0.0653   0.1851910   0.4326280
   8     0.9619500  #070707    8 1  0.0730   0.1855710   0.4350780
   9     1.0185580  #080808    9 1  0.0572   0.1854860   0.4370180
  10     1.0870190  #090909   10 1  0.0650   0.1859990   0.4387930
  11     1.1533170  #0a0a0a   11 1  0.0592   0.1861630   0.4405870
  12     1.2284630  #0b0b0b   12 1  0.0631   0.1866460   0.4424840
  13     1.2982720  #0c0c0c   13 1  0.0553   0.1873930   0.4437580
  14     1.3786300  #0d0d0d   14 1  0.0600   0.1875840   0.4454150
  15     1.4572180  #0e0e0e   15 1  0.0554   0.1874190   0.4466680
  16     1.5457950  #0f0f0f   16 1  0.0590   0.1878990   0.4480520
  17     1.6221460  #101010   17 1  0.0482   0.1873810   0.4490170
  18     1.7047090  #111111   18 1  0.0496   0.1881950   0.4499640
  19     1.8076520  #121212   19 1  0.0586   0.1882620   0.4510190
  20     1.8837190  #131313   20 1  0.0412   0.1888480   0.4516720
  21     1.9940800  #141414   21 1  0.0569   0.1881280   0.4529850
  22     2.1071910  #151515   22 1  0.0552   0.1890310   0.4535250
  23     2.1991990  #161616   23 1  0.0427   0.1891510   0.4544910
  24     2.3133640  #171717   24 1  0.0506   0.1888460   0.4551470
  25     2.4202140  #181818   25 1  0.0451   0.1886210   0.4556850
  26     2.5325880  #191919   26 1  0.0454   0.1894610   0.4559490
  27     2.6538330  #1a1a1a   27 1  0.0468   0.1897080   0.4566570
  28     2.7760920  #1b1b1b   28 1  0.0450   0.1898810   0.4570010
  29     2.8896460  #1c1c1c   29 1  0.0401   0.1897310   0.4577860
  30     3.0177410  #1d1d1d   30 1  0.0434   0.1898070   0.4579840
  31     3.1323330  #1e1e1e   31 1  0.0373   0.1899660   0.4584240
  32     3.2793160  #1f1f1f   32 1  0.0458   0.1896300   0.4590020
  33     3.4287030  #202020   33 1  0.0445   0.1901100   0.4593670
  34     3.5644530  #212121   34 1  0.0388   0.1904580   0.4594830
  35     3.6989430  #222222   35 1  0.0370   0.1899120   0.4599440
  36     3.8496390  #232323   36 1  0.0399   0.1900270   0.4604280
  37     3.9906670  #242424   37 1  0.0360   0.1902700   0.4605170
  38     4.1728360  #252525   38 1  0.0446   0.1901320   0.4613300
  39     4.3158290  #262626   39 1  0.0337   0.1903770   0.4613020
  40     4.4649230  #272727   40 1  0.0340   0.1909300   0.4613460
  41     4.6595600  #282828   41 1  0.0427   0.1900750   0.4618760
  42     4.8245890  #292929   42 1  0.0348   0.1902430   0.4620920
  43     5.0023150  #2a2a2a   43 1  0.0362   0.1909080   0.4622900
  44     5.1858520  #2b2b2b   44 1  0.0360   0.1910530   0.4622740
  45     5.3547130  #2c2c2c   45 1  0.0320   0.1909660   0.4630710
  46     5.5438840  #2d2d2d   46 1  0.0347   0.1904750   0.4632360
  47     5.7287520  #2e2e2e   47 1  0.0328   0.1910700   0.4631390
  48     5.9064870  #2f2f2f   48 1  0.0306   0.1909710   0.4628780
  49     6.1180320  #303030   49 1  0.0352   0.1905870   0.4633740
  50     6.2999520  #313131   50 1  0.0293   0.1910520   0.4634700
  51     6.5341140  #323232   51 1  0.0365   0.1912140   0.4637760
  52     6.7593270  #333333   52 1  0.0339   0.1907600   0.4642450
  53     6.9622530  #343434   53 1  0.0296   0.1912600   0.4640920
  54     7.2073620  #353535   54 1  0.0346   0.1909330   0.4644130
  55     7.4618030  #363636   55 1  0.0347   0.1907790   0.4646070
  56     7.6420920  #373737   56 1  0.0239   0.1914990   0.4645260
  57     7.9025250  #383838   57 1  0.0335   0.1909560   0.4648470
  58     8.1807980  #393939   58 1  0.0346   0.1911630   0.4649910
  59     8.3499860  #3a3a3a   59 1  0.0205   0.1904820   0.4650120
  60     8.6151860  #3b3b3b   60 1  0.0313   0.1907610   0.4649750
  61     8.8670520  #3c3c3c   61 1  0.0288   0.1910900   0.4652990
  62     9.1579770  #3d3d3d   62 1  0.0323   0.1900300   0.4653960
  63     9.4268360  #3e3e3e   63 1  0.0289   0.1910930   0.4656640
  64     9.7072880  #3f3f3f   64 1  0.0293   0.1908490   0.4657500
  65    10.0078900  #404040   65 1  0.0305   0.1911590   0.4656480
  66    10.2476980  #414141   66 1  0.0237   0.1903540   0.4652510
  67    10.6140990  #424242   67 1  0.0351   0.1910600   0.4658310
  68    10.9179140  #434343   68 1  0.0282   0.1913850   0.4656800
  69    11.2299690  #444444   69 1  0.0282   0.1918490   0.4660520
  70    11.5438760  #454545   70 1  0.0276   0.1915170   0.4658240
  71    11.8563660  #464646   71 1  0.0267   0.1905380   0.4662870
  72    12.1656570  #474747   72 1  0.0258   0.1914060   0.4659560
  73    12.4827590  #484848   73 1  0.0257   0.1921410   0.4662100
  74    12.8313230  #494949   74 1  0.0275   0.1904270   0.4661310
  75    13.1754190  #4a4a4a   75 1  0.0265   0.1911510   0.4663620
  76    13.5341380  #4b4b4b   76 1  0.0269   0.1913980   0.4666840
  77    13.8971880  #4c4c4c   77 1  0.0265   0.1925030   0.4664160
  78    14.1875970  #4d4d4d   78 1  0.0207   0.1902800   0.4659550
  79    14.6735280  #4e4e4e   79 1  0.0337   0.1918110   0.4666440
  80    15.0922760  #4f4f4f   80 1  0.0281   0.1933900   0.4662760
  81    15.4521920  #505050   81 1  0.0236   0.1911540   0.4667080
  82    15.8650240  #515151   82 1  0.0264   0.1910480   0.4671010
  83    16.2965240  #525252   83 1  0.0268   0.1922420   0.4666980
  84    16.6984270  #535353   84 1  0.0244   0.1908130   0.4669980
  85    17.0726300  #545454   85 1  0.0222   0.1917470   0.4663790
  86    17.5237010  #555555   86 1  0.0261   0.1907840   0.4668680
  87    18.0765880  #565656   87 1  0.0311   0.1906380   0.4672130
  88    18.3498690  #575757   88 1  0.0150   0.1907600   0.4666260
  89    18.7365030  #585858   89 1  0.0209   0.1912840   0.4665240
  90    19.2816460  #595959   90 1  0.0287   0.1913620   0.4664000
  91    19.8597150  #5a5a5a   91 1  0.0295   0.1919130   0.4675130
  92    20.2117290  #5b5b5b   92 1  0.0176   0.1917550   0.4673020
  93    20.7222600  #5c5c5c   93 1  0.0249   0.1912100   0.4670630
  94    21.0747010  #5d5d5d   94 1  0.0169   0.1911080   0.4666010
  95    21.8119350  #5e5e5e   95 1  0.0344   0.1913010   0.4671880
  96    22.2427100  #5f5f5f   96 1  0.0196   0.1909440   0.4672810
  97    22.6296890  #606060   97 1  0.0172   0.1914030   0.4669830
  98    23.0615560  #616161   98 1  0.0189   0.1911450   0.4664510
  99    23.9114020  #626262   99 1  0.0362   0.1915800   0.4677650
 100    24.2293950  #636363  100 1  0.0132   0.1909800   0.4671750
 101    24.6954820  #646464  101 1  0.0191   0.1912250   0.4669700
 102    25.3545690  #656565  102 1  0.0263   0.1916270   0.4668980
 103    26.1706170  #666666  103 1  0.0317   0.1915870   0.4675920
 104    26.7151990  #676767  104 1  0.0206   0.1915990   0.4677590
 105    27.4187510  #686868  105 1  0.0260   0.1913430   0.4676700
 106    27.5787020  #696969  106 1  0.0058   0.1911440   0.4669540
 107    28.2384040  #6a6a6a  107 1  0.0236   0.1915470   0.4666020
 108    29.2119340  #6b6b6b  108 1  0.0339   0.1911690   0.4676800
 109    29.7561530  #6c6c6c  109 1  0.0185   0.1911640   0.4679900
 110    30.2244440  #6d6d6d  110 1  0.0156   0.1914960   0.4668440
 111    31.1978150  #6e6e6e  111 1  0.0317   0.1911340   0.4679140
 112    31.6643800  #6f6f6f  112 1  0.0148   0.1913520   0.4675420
 113    32.1300800  #707070  113 1  0.0146   0.1915130   0.4675380
 114    33.2194210  #717171  114 1  0.0333   0.1915450   0.4677380
 115    33.6528120  #727272  115 1  0.0130   0.1914480   0.4667630
 116    34.3093340  #737373  116 1  0.0193   0.1916040   0.4677040
 117    35.0919470  #747474  117 1  0.0226   0.1912780   0.4676990
 118    36.1027570  #757575  118 1  0.0284   0.1914630   0.4676220
 119    36.5688210  #767676  119 1  0.0128   0.1916210   0.4674850
 120    37.7821260  #777777  120 1  0.0326   0.1911000   0.4675660
 121    38.5200080  #787878  121 1  0.0193   0.1912400   0.4676580
 122    39.4163650  #797979  122 1  0.0230   0.1911670   0.4677410
 123    40.0755650  #7a7a7a  123 1  0.0166   0.1914280   0.4676450
 124    41.3235320  #7b7b7b  124 1  0.0307   0.1912640   0.4677490
 125    42.0267520  #7c7c7c  125 1  0.0169   0.1910880   0.4677960
 126    43.1520170  #7d7d7d  126 1  0.0264   0.1914700   0.4675890
 127    44.0483730  #7e7e7e  127 1  0.0206   0.1914000   0.4676640
 128    44.3201920  #7f7f7f  128 1  0.0062   0.1913850   0.4678560
 129    45.5241390  #808080  129 1  0.0268   0.1916270   0.4678170
 130    46.3869420  #818181  130 1  0.0188   0.1913290   0.4675360
 131    47.3966430  #828282  131 1  0.0215   0.1914260   0.4677910
 132    48.4861360  #838383  132 1  0.0227   0.1914550   0.4678810
 133    49.5420760  #848484  133 1  0.0215   0.1912680   0.4676410
 134    50.1214840  #858585  134 1  0.0116   0.1915370   0.4677140
 135    51.8008530  #868686  135 1  0.0330   0.1912700   0.4676710
 136    52.3455990  #878787  136 1  0.0105   0.1912850   0.4677140
 137    53.1181440  #888888  137 1  0.0147   0.1916230   0.4678050
 138    54.9559860  #898989  138 1  0.0340   0.1912180   0.4677570
 139    56.1599330  #8a8a8a  139 1  0.0217   0.1914190   0.4677280
 140    56.6248880  #8b8b8b  140 1  0.0082   0.1914860   0.4678990
 141    57.9526460  #8c8c8c  141 1  0.0232   0.1913140   0.4678380
 142    59.7013400  #8d8d8d  142 1  0.0297   0.1915130   0.4678450
 143    60.3247680  #8e8e8e  143 1  0.0104   0.1914390   0.4680010
 144    61.7669800  #8f8f8f  144 1  0.0236   0.1914330   0.4678430
 145    62.3557470  #909090  145 1  0.0095   0.1911590   0.4679710
 146    63.7528300  #919191  146 1  0.0222   0.1914070   0.4679590
 147    65.5466520  #929292  147 1  0.0277   0.1913460   0.4678260
 148    66.3989890  #939393  148 1  0.0129   0.1915690   0.4677860
 149    68.2714930  #949494  149 1  0.0278   0.1914310   0.4677690
 150    68.7804680  #959595  150 1  0.0074   0.1912270   0.4679930
 151    70.7234070  #969696  151 1  0.0279   0.1914900   0.4678040
 152    72.2085300  #979797  152 1  0.0208   0.1912100   0.4679580
 153    73.6056130  #989898  153 1  0.0192   0.1914240   0.4679480
 154    74.9680330  #999999  154 1  0.0183   0.1914610   0.4679190
 155    76.0228640  #9a9a9a  155 1  0.0140   0.1913120   0.4679560
 156    77.2268110  #9b9b9b  156 1  0.0157   0.1914560   0.4679310
 157    79.1339780  #9c9c9c  157 1  0.0244   0.1915000   0.4679310
 158    80.6988920  #9d9d9d  158 1  0.0196   0.1912100   0.4679740
 159    82.8789870  #9e9e9e  159 1  0.0267   0.1912750   0.4678960
 160    83.7313230  #9f9f9f  160 1  0.0102   0.1914520   0.4678630
 161    85.7969640  #a0a0a0  161 1  0.0244   0.1913960   0.4678620
 162    87.8626050  #a1a1a1  162 1  0.0238   0.1913430   0.4678600
 163    88.9520980  #a2a2a2  163 1  0.0123   0.1913600   0.4679080
 164    90.8592650  #a3a3a3  164 1  0.0212   0.1914000   0.4679090
 165    91.8354130  #a4a4a4  165 1  0.0107   0.1913330   0.4678600
 166    94.5602540  #a5a5a5  166 1  0.0292   0.1913950   0.4678180
 167    95.6497470  #a6a6a6  167 1  0.0115   0.1914100   0.4678630
 168    97.4771230  #a7a7a7  168 1  0.0189   0.1914780   0.4679410
 169   100.0528480  #a8a8a8  169 1  0.0261   0.1913100   0.4679450
 170   101.0636580  #a9a9a9  170 1  0.0101   0.1913750   0.4679140
 171   102.4260790  #aaaaaa  171 1  0.0134   0.1914030   0.4678940
 172   105.8541400  #ababab  172 1  0.0329   0.1913860   0.4678730
 173   106.8649510  #acacac  173 1  0.0095   0.1914470   0.4678450
 174   108.3060540  #adadad  174 1  0.0134   0.1914250   0.4678930
 175   110.5648310  #aeaeae  175 1  0.0206   0.1914230   0.4679020
 176   112.5171270  #afafaf  176 1  0.0175   0.1913140   0.4678230
 177   114.5827680  #b0b0b0  177 1  0.0182   0.1912750   0.4678230
 178   116.6830710  #b1b1b1  178 1  0.0182   0.1913450   0.4678350
 179   119.2147760  #b2b2b2  179 1  0.0215   0.1913560   0.4677920
 180   121.4735530  #b3b3b3  180 1  0.0188   0.1913550   0.4678020
 181   124.7431410  #b4b4b4  181 1  0.0266   0.1914070   0.4677880
 182   126.3427180  #b5b5b5  182 1  0.0127   0.1913240   0.4678280
 183   129.7707790  #b6b6b6  183 1  0.0268   0.1913120   0.4678130
 184   132.0295570  #b7b7b7  184 1  0.0173   0.1913120   0.4678220
 185   134.4027880  #b8b8b8  185 1  0.0178   0.1913830   0.4677850
 186   135.6507540  #b9b9b9  186 1  0.0092   0.1913330   0.4678160
 187   139.6235620  #bababa  187 1  0.0289   0.1913270   0.4678170
 188   141.5307290  #bbbbbb  188 1  0.0136   0.1913530   0.4678180
 189   143.7906160  #bcbcbc  189 1  0.0158   0.1913670   0.4677240
 190   146.5583680  #bdbdbd  190 1  0.0191   0.1912700   0.4678390
 191   149.1247350  #bebebe  191 1  0.0174   0.1913650   0.4678140
 192   150.5669470  #bfbfbf  192 1  0.0096   0.1913640   0.4677510
 193   153.2917880  #c0c0c0  193 1  0.0179   0.1914010   0.4677270
 194   157.9331540  #c1c1c1  194 1  0.0298   0.1912660   0.4677340
 195   161.1229500  #c2c2c2  195 1  0.0200   0.1913280   0.4677710
 196   162.5651620  #c3c3c3  196 1  0.0089   0.1913270   0.4677130
 197   165.3675770  #c4c4c4  197 1  0.0171   0.1913190   0.4678240
 198   168.3306830  #c5c5c5  198 1  0.0178   0.1912860   0.4677550
 199   173.3594310  #c6c6c6  199 1  0.0294   0.1912300   0.4676900
 200   176.4705450  #c7c7c7  200 1  0.0178   0.1913160   0.4676830
 201   177.4455840  #c8c8c8  201 1  0.0055   0.1912700   0.4677420
 202   181.8844560  #c9c9c9  202 1  0.0247   0.1912990   0.4677170
 203   186.2446450  #cacaca  203 1  0.0237   0.1913540   0.4676540
 204   189.5235900  #cbcbcb  204 1  0.0175   0.1912280   0.4676710
 205   190.2625820  #cccccc  205 1  0.0039   0.1912660   0.4676120
 206   193.8837800  #cdcdcd  206 1  0.0189   0.1912820   0.4676120
 207   199.6493010  #cecece  207 1  0.0293   0.1912500   0.4676500
 208   200.6612200  #cfcfcf  208 1  0.0051   0.1912930   0.4675630
 209   206.5411950  #d0d0d0  209 1  0.0289   0.1913080   0.4675720
 210   210.0479390  #d1d1d1  210 1  0.0168   0.1912760   0.4676010
 211   213.4771100  #d2d2d2  211 1  0.0162   0.1912790   0.4675260
 212   217.0625360  #d3d3d3  212 1  0.0167   0.1912250   0.4675880
 213   221.2295890  #d4d4d4  213 1  0.0190   0.1912530   0.4675320
 214   226.1785450  #d5d5d5  214 1  0.0221   0.1912240   0.4675200
 215   226.9962190  #d6d6d6  215 1  0.0036   0.1912340   0.4675030
 216   232.1383120  #d7d7d7  216 1  0.0224   0.1912260   0.4674970
 217   237.6677860  #d8d8d8  217 1  0.0235   0.1912640   0.4674400
 218   240.5511010  #d9d9d9  218 1  0.0121   0.1912550   0.4674280
 219   243.4355250  #dadada  219 1  0.0119   0.1912550   0.4673550
 220   250.8363940  #dbdbdb  220 1  0.0299   0.1912470   0.4673610
 221   252.0854700  #dcdcdc  221 1  0.0050   0.1912290   0.4673210
 222   259.7257140  #dddddd  222 1  0.0299   0.1911870   0.4672430
 223   262.2574190  #dedede  223 1  0.0097   0.1911930   0.4672290
 224   268.8417230  #dfdfdf  224 1  0.0248   0.1911870   0.4671970
 225   270.4424090  #e0e0e0  225 1  0.0059   0.1911570   0.4671650
 226   276.0516740  #e1e1e1  226 1  0.0205   0.1911810   0.4670960
 227   282.0565690  #e2e2e2  227 1  0.0215   0.1911270   0.4670550
 228   284.9398850  #e3e3e3  228 1  0.0102   0.1911210   0.4670480
 229   291.9913620  #e4e4e4  229 1  0.0244   0.1911440   0.4669570
 230   298.3385100  #e5e5e5  230 1  0.0215   0.1911840   0.4669100
 231   299.2811050  #e6e6e6  231 1  0.0032   0.1911290   0.4668450
 232   304.5029880  #e7e7e7  232 1  0.0173   0.1911140   0.4668270
 233   309.6472990  #e8e8e8  233 1  0.0168   0.1911230   0.4667390
 234   315.2565640  #e9e9e9  234 1  0.0180   0.1911440   0.4666870
 235   321.1018760  #eaeaea  235 1  0.0184   0.1911170   0.4667040
 236   326.5989060  #ebebeb  236 1  0.0170   0.1911200   0.4665820
 237   334.8647970  #ececec  237 1  0.0250   0.1910900   0.4664810
 238   339.3845690  #ededed  238 1  0.0134   0.1911050   0.4664190
 239   345.5050270  #eeeeee  239 1  0.0179   0.1910960   0.4663380
 240   349.7161010  #efefef  240 1  0.0121   0.1910640   0.4663340
 241   358.5614000  #f0f0f0  241 1  0.0250   0.1910750   0.4662580
 242   365.3850790  #f1f1f1  242 1  0.0189   0.1910480   0.4661920
 243   372.9917690  #f2f2f2  243 1  0.0206   0.1909940   0.4661180
 244   376.1491210  #f3f3f3  244 1  0.0084   0.1909990   0.4660660
 245   384.8810760  #f4f4f4  245 1  0.0229   0.1909910   0.4659780
 246   387.4936810  #f5f5f5  246 1  0.0068   0.1909940   0.4659210
 247   399.4281160  #f6f6f6  247 1  0.0303   0.1909520   0.4657700
 248   401.6555580  #f7f7f7  248 1  0.0056   0.1909380   0.4656720
 249   413.2719370  #f8f8f8  249 1  0.0285   0.1909340   0.4655680
 250   419.2801600  #f9f9f9  250 1  0.0144   0.1909160   0.4654580
 251   422.8711310  #fafafa  251 1  0.0085   0.1909160   0.4653350
 252   434.9640400  #fbfbfb  252 1  0.0282   0.1908610   0.4652140
 253   441.4047740  #fcfcfc  253 1  0.0147   0.1908350   0.4650690
 254   450.1400550  #fdfdfd  254 1  0.0196   0.1908450   0.4649170
 255   458.3410570  #fefefe  255 1  0.0181   0.1907900   0.4647400
 256   466.3373470  #ffffff  256 1  0.0173   0.1907840   0.4646190

**Comment by jonathancolledge** [comment]
#  lumResponse vers. 2.1 - 03/11/2020 22:27:45
#  Display ID: 
#  iLdelay=1  avgN=1  ILlimit_plus=0.20 ILlimit_minus=-0.05  Meter=i1DisplayPro
#  0.171445  #000000
#  0.171257  #000000
#  0.170573  #000000
   1    0.234  #050505    1 1  0.0000   0.2888   0.3027
   2    0.520  #0b0b0b    1 2  0.7581   0.3306   0.3414
   3    1.396  #151515    2 1  0.9139   0.3493   0.3619
   4    1.977  #1b1b1b    2 2  0.3446   0.3438   0.3593
   5    3.091  #252525    3 1  0.4397   0.3482   0.3605
   6    3.863  #2b2b2b    3 2  0.2219   0.3519   0.3638
   7    5.461  #353535    4 1  0.3428   0.3587   0.3663
   8    6.616  #3b3b3b    4 2  0.1912   0.3622   0.3679
   9    8.909  #454545    5 1  0.2954   0.3696   0.3715
  10   10.596  #4b4b4b    5 2  0.1730   0.3719   0.3737
  11   13.898  #555555    6 1  0.2696   0.3762   0.3775
  12   15.983  #5b5b5b    6 2  0.1396   0.3761   0.3781
  13   20.103  #656565    7 1  0.2283   0.3779   0.3794
  14   22.801  #6b6b6b    7 2  0.1258   0.3764   0.3799
  15   27.601  #757575    8 1  0.1904   0.3776   0.3799
  16   30.607  #7b7b7b    8 2  0.1033   0.3759   0.3789
  17   36.119  #858585    9 1  0.1652   0.3741   0.3788
  18   39.771  #8b8b8b    9 2  0.0963   0.3744   0.3791
  19   45.729  #959595   10 1  0.1394   0.3745   0.3781
  20   49.541  #9b9b9b   10 2  0.0800   0.3739   0.3777
  21   56.576  #a5a5a5   11 1  0.1326   0.3740   0.3772
  22   61.070  #ababab   11 2  0.0764   0.3744   0.3768
  23   68.606  #b5b5b5   12 1  0.1162   0.3741   0.3758
  24   73.598  #bbbbbb   12 2  0.0702   0.3747   0.3762
  25   82.269  #c5c5c5   13 1  0.1113   0.3758   0.3761
  26   87.795  #cbcbcb   13 2  0.0650   0.3764   0.3763
  27   96.891  #d5d5d5   14 1  0.0985   0.3752   0.3763
  28  103.162  #dbdbdb   14 2  0.0627   0.3753   0.3769
  29  113.648  #e5e5e5   15 1  0.0967   0.3757   0.3767
  30  118.035  #ebebeb   15 2  0.0379   0.3699   0.3783
  31  125.319  #f5f5f5   16 1  0.0599   0.3600   0.3805
  32  128.930  #fbfbfb   16 2  0.0284   0.3549   0.3808
  33  131.697  #ffffff   17 1  0.0212   0.3511   0.3804

**Comment by nickbevins** [comment]
Sorry I'm just getting to this - 

Are you only seeing this issue when running the 256 mode? Which plots are you trying to see? 

I know you closed it, but feel free to re-open if it's an issue and I'll try to look into it.

**Comment by jonathancolledge** [comment]
Ah, yes, only 256, I realised that I had always previously used 16x2 or
18x1, so thought it might be by design. Is 256 supposed to work too?

Thanks,

Jonathan
