### ISSUE TITLE
PACS Display and NDS CXtra

### ISSUE THREAD

**Issue by tech-avid** [pacsdisplay/pacsdisplay#5]
I think PACS Display and the NDS CXtra v6.6.3 (1/11/2016) interfere with each other. I like to confirm whether the CXtra readings are accurate or not with the QC measurement. When I run the lum response and i1meter program it gives an error message when CXtra is running and then Cxtra gives and error message when trying to run the Rightlight calibration. I have to uninstall and reinstall CXtra to get it to work. 
When running CXtra Rightlight calibration and Front sensor conformance testing on the NDS S3c, the maximum brightness I set and measure is 385 cd/m2. When I run the i1meter on a laptop and and measure the NDS S3c screen running from a desktop computer, the brightness is about 350 cd/m2. 

For an Eizo RX340 set to about 400 cd/m2, the i1meter measures about 400 cd/m2 so that is accurate. Luckily it does not interfere with the Eizo RadicsLE software. 

Thank you for writing such a great software!

**Comment by nickbevins** [comment]
Are you using the same photometer to operate in both CXtra and i1meter? Can you also confirm which version of pacsdisplay you're running? 

The i1meter application just makes a single call to the spotread command line executable, which returns the luminance/illuminance measurement for parsing. The only chance for interference would be if another application is actively using the same meter. I don't have anything that uses the CXtra software to test, so I'm unable to debug what may be happening. 

I'm going to close this issue, but please feel free to move it to the discussion if you'd like to give any updates. 

Thanks - Nick

**Comment by tech-avid** [comment]
I am using PacsDisplay version 5Db.
The CXtra program uses the NDS Dome S3c built in back sensor and built in front sensor. I wish it could use the i1Display Pro as an external photometer, but it is not compatible. It requires a much more expensive proprietary NDS II photometer.
My work around is to reboot my computer which is an annoyance, but it fixes the issue.
Thanks for the feedback.
Sam

________________________________

**Comment by tech-avid** [comment]
I started off uninstalling and reinstalling programs and figured out that just unplugging and plugging back in the colorimeter again often fixes this. I should have started off with the simple steps first.
Thanks,
Sam

________________________________
