### ISSUE TITLE
[Not an issue] Locate source code for loadLUT, way to contact

### ISSUE THREAD

**Issue by braggpeaks** [pacsdisplay/pacsdisplay#6]
Hi Nick and rest of team, I was looking for an option to get in contact with you, but didn't really find one. Thanks for your contributions! I'm looking for the source of the command line program written in C that is used to load LUTs to the graphic driver (loadLUT) - it sounds as if this would be open source, but I couldn't locate it. Thanks, Daniel

**Comment by nickbevins** [comment]
Hi Daniel - I uploaded the code on github in the pacsdisplay/pacsDisplay/pacsDisplay-BIN/loadLUT/ directory. I've never modified or even looked at it, so I won't be much help with it.
